export const PLAY_STREAM = 'PLAY_STREAM';
export const PLAYER_OPEN = 'PLAYER_OPEN';
export const PLAYER_CLOSE = 'PLAYER_CLOSE';
export const NEXT_STREAM = 'NEXT_STREAM';
export const PREVIOUS_STREAM = 'PREVIOUS_STREAM';